import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { config, publicUrl, type ServiceRecord } from "../config.js";
import type { IntegrationResult } from "./pihole.js";

function siteBlock(service: ServiceRecord): string {
  // Public URL is https://hostname via Caddy; backends (e.g. Vite) are HTTP.
  // Rewrite Host to the upstream so Vite's allowedHosts check does not 403.
  const upstreamHost = service.port
    ? `${service.ip}:${service.port}`
    : service.ip;
  const upstream = `http://${upstreamHost}`;

  return `${service.hostname} {
\ttls internal
\treverse_proxy ${upstream} {
\t\theader_up Host ${upstreamHost}
\t\theader_up X-Forwarded-Host {host}
\t\theader_up X-Forwarded-Proto {scheme}
\t}
}
`;
}

function snippetZones(): string[] | null {
  const raw = config.caddySnippetZones;
  if (!raw.length) return null; // null = all proxied services
  return raw;
}

function includeInSnippet(service: ServiceRecord): boolean {
  if (!service.proxy || service.paused) return false;
  const zones = snippetZones();
  if (!zones) return true;
  return zones.includes(service.zone.toLowerCase());
}

export function renderCaddySnippet(services: ServiceRecord[]): string {
  const proxied = services.filter(includeInSnippet);
  const zoneNote = snippetZones()
    ? `# Zones: ${snippetZones()!.join(", ")}\n`
    : "# Zones: all proxied services\n";
  const header = `# Generated by HomeArpaDashboard — do not edit by hand
# Import from your Caddyfile, e.g.:
#   import /etc/caddy/arpa-dashboard.caddy
${zoneNote}#
`;
  if (proxied.length === 0) {
    return `${header}# (no proxied services)\n`;
  }
  return header + proxied.map(siteBlock).join("\n");
}

async function reloadCaddy(): Promise<string | undefined> {
  if (!config.caddyAdminUrl || !config.caddyCaddyfilePath) {
    return undefined;
  }

  const caddyfile = await readFile(
    path.resolve(config.caddyCaddyfilePath),
    "utf8",
  );
  const url = `${config.caddyAdminUrl.replace(/\/$/, "")}/load`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "text/caddyfile" },
    body: caddyfile,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Caddy reload failed HTTP ${res.status}${text ? `: ${text.slice(0, 200)}` : ""}`,
    );
  }
  return `reloaded via ${url}`;
}

export async function syncCaddySnippet(
  services: ServiceRecord[],
): Promise<IntegrationResult> {
  if (!config.caddySnippetPath) {
    return {
      ok: true,
      skipped: true,
      detail: "Caddy snippet path not configured (set CADDY_SNIPPET_PATH)",
    };
  }

  if (config.dryRunIntegrations) {
    return {
      ok: true,
      skipped: true,
      detail: `dry-run: would write ${config.caddySnippetPath}`,
    };
  }

  const file = path.resolve(config.caddySnippetPath);
  await mkdir(path.dirname(file), { recursive: true });
  const body = renderCaddySnippet(services);
  await writeFile(file, body, "utf8");

  const count = services.filter(includeInSnippet).length;
  let detail = `Wrote Caddy snippet (${count} sites) → ${file}`;

  try {
    const reloadDetail = await reloadCaddy();
    if (reloadDetail) detail += `; ${reloadDetail}`;
  } catch (err) {
    return {
      ok: false,
      detail: `${detail}; reload error: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  return { ok: true, detail };
}

export function dashboardPayload(services: ServiceRecord[]) {
  return services.map((s) => ({
    ...s,
    href: publicUrl(s),
  }));
}
